### PR TITLE
App session option and updates

### PR DESCRIPTION
**Pull request by krimin-killr21**
Added THIS_APP_SESSION option which allows the dev to specify that something should only happen once per app session, that is, once for every time that the app is started from scratch.

 Also updated the support lib and build tools.

### CODE REVIEW

**Comment by krimin-killr21** [comment]
If needed you can roll back the android version (the cause of the failed check).

**Comment by jonfinerty** [comment]
Hi, thanks the for PR!

I've had a brief look and it seems good, I'll have a better review and merge in the next couple of days. Just need to update the travis.yml file for the failed checked.

**Comment by krimin-killr21** [comment]
No problem!

**Comment by jonfinerty** [comment]
Ok, I've had a look through, just a few small things.

Could you add a few tests around this in `https://github.com/jonfinerty/Once/blob/master/once/src/test/java/jonathanfinerty/once/OnceTests.java` 

And can you bump the values in https://github.com/jonfinerty/Once/blob/master/.travis.yml so that the build passes on this branch.

Also, implementation wise, it might be nice rather than storing a list of all the tags ever seen in an arraylist, we could re-use the existing timestamp based system. i.e. Grab the timestamp when `initialise` was called and check any tags since then, like how it works with updates. Don't worry about changing to this way if you don't want to, just a thought.

**Comment by krimin-killr21** [comment]
I'll work on the other stuff. The reason I didn't go with the approach you're suggesting is illustrated in this situation:

- Session A is started by launching the app from the launcher.

- The Session A button is pressed and responds. (The button should not respond again in Session A)

- Session B is opened by a share intent from another app. Nothing is pressed. However, because a new session is started, the button is reset.

- The user navigates back to Session A and presses the button. Despite already having been pressed in Session A, it responds, because Session B was started after Session A.

**Comment by jonfinerty** [comment]
Looks good, merging. Thanks for your patience.

**Pull request merged**
